### ISSUE TITLE
Word of caution with respect to the hentai module

### ISSUE THREAD

**Issue by hentai-chan** [hysrx/nhclientai#1]
Just as a heads up, as it might have escaped your attention, version 1.1 of hentai explicitly uses python version 3.8 or higher and will throw an exception for any version lower than that:

```python
try:
    assert sys.version_info.major == 3
    assert sys.version_info.minor > 7
except AssertionError:
    raise RuntimeError("Hentai requires Python 3.8+!") 
```

Reason being that I am using a new built-in module ([dataclasses](https://docs.python.org/3.8/library/dataclasses.html)) that didn't exist in 3.6. So you will run into issues here if you want to work with 3.6. I should probably have mentioned that at the top of my readme file, though. Lesson learned.

What now? There's a [backport ](https://pypi.org/project/dataclasses/) for 3.6 but I'd have to test and accomodate for this in my next release. Let me know if you need support for 3.6 and I'll see if I can get this to work this week. Alternatively, consider upgrading to 3.8 if possible.

**Comment by hysrx** [comment]
Hello! Sorry for not looking deeper into your package, lesson learnt for me too. The reason this and most of my projects have a usual minimum version of 3.6 is that I try to incorporate PyPy.

Thankfully, PyPy has updated to v7.3.2 with (alpha) 3.7 support, which do support dataclasses as depicted in the [official library page](https://docs.python.org/3/library/dataclasses.html). I will be doing more specific testing on this matter later though.
